/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command = {
  op: "workspace_refresh";
};
export type WorkspaceGeneration = number;
export type WorkspaceEventKind = "stale" | "refreshed" | "notes" | "git_base";
export type Query =
  | {
      op: "workspace_status";
    }
  | {
      depth: number;
      lang: string[];
      op: "tree_children";
      path: string[];
      projection: string[];
      workspace?: string | null;
    }
  | {
      context_lines: number;
      include_code: boolean;
      include_non_navigable: boolean;
      kind: string[];
      lang: string[];
      name?: string | null;
      op: "symbol_search";
      path: string[];
      projection: string[];
      shape: string[];
      text?: string | null;
      workspace?: string | null;
    }
  | {
      context_lines: number;
      include_code: boolean;
      include_non_navigable: boolean;
      kind: string[];
      lang: string[];
      name?: string | null;
      op: "symbol_insights";
      path: string[];
      projection: string[];
      shape: string[];
      text?: string | null;
      workspace?: string | null;
    }
  | {
      context_lines: number;
      op: "symbol_detail";
      uri: string;
      workspace?: string | null;
    }
  | {
      direction: UsageDirection;
      lang: string[];
      op: "symbol_usages";
      path: string[];
      projection: string[];
      uri: string;
      workspace?: string | null;
    }
  | {
      context_lines: number;
      include_code: boolean;
      op: "view_read";
      scheme?: string | null;
      uri: string;
    }
  | {
      lang: string[];
      op: "rules_list";
      profile?: string | null;
      rules?: string | null;
      severity: string[];
      workspace?: string | null;
    }
  | {
      file: string[];
      op: "rules_check";
      profile?: string | null;
      report: boolean;
      rules?: string | null;
      workspace?: string | null;
    }
  | {
      op: "change_review";
      workspace?: string | null;
    }
  | {
      action: NotesAction;
      body?: string | null;
      created_by?: string | null;
      id?: string | null;
      include_done: boolean;
      kind?: string | null;
      moniker?: string | null;
      op: "notes";
      orphan?: boolean | null;
      status?: string | null;
      title?: string | null;
    };
export type UsageDirection = "incoming" | "outgoing" | "both";
export type NotesAction = "list" | "get" | "create" | "update" | "transition" | "delete";
export type Consistency = "current" | "refresh_if_stale" | "stale_ok";
export type QueryResult =
  | {
      data: WorkspaceStatus;
      kind: "workspace_status";
    }
  | {
      data: TreeChildrenResult;
      kind: "tree_children";
    }
  | {
      data: SymbolListResult;
      kind: "symbol_list";
    }
  | {
      data: SymbolInsightsResult;
      kind: "symbol_insights";
    }
  | {
      data: SymbolDetailResult;
      kind: "symbol_detail";
    }
  | {
      data: SymbolUsagesResult;
      kind: "symbol_usages";
    }
  | {
      data: ViewReadResult;
      kind: "view_read";
    }
  | {
      data: RulesListResult;
      kind: "rules_list";
    }
  | {
      data: RulesCheckResult;
      kind: "rules_check";
    }
  | {
      data: ChangeReviewResult;
      kind: "change_review";
    }
  | {
      data: NotesResult;
      kind: "notes";
    };
export type TreeNodeKind = "file" | "directory";
export type ViewReadResult =
  | {
      kind: "list";
      views: ViewSummaryDto[];
    }
  | {
      anchor: string;
      boundaries: ViewBoundaryDto[];
      fragment: string;
      gotchas: ViewGotchaDto[];
      id: string;
      intent?: string | null;
      kind: "detail";
      rules: ViewRuleDto[];
      scope: string;
      summary?: string | null;
      title?: string | null;
    };
export type NoteResolutionDto =
  | {
      file: string;
      /**
       * @minItems 2
       * @maxItems 2
       */
      slice?: [number, number] | null;
      status: "resolved";
      target: string;
    }
  | {
      status: "orphan";
    };

/**
 * Umbrella over every root RPC type, used only to emit a single JSON Schema document (`export-schema`) whose definitions cover the whole wire contract.
 */
export interface DaemonProtocol {
  command_request: CommandRequest;
  command_response: CommandResponse;
  error: QueryError;
  event: WorkspaceEventDto;
  handshake: HandshakeResponse;
  query: Query;
  query_request: QueryRequest;
  query_response: QueryResponse;
  query_result: QueryResult;
  registry_entry: DaemonRegistryEntry;
  workspace_config: DaemonWorkspaceConfig;
}
export interface CommandRequest {
  command: Command;
}
export interface CommandResponse {
  generation?: WorkspaceGeneration | null;
  message: string;
  status?: WorkspaceStatus | null;
}
export interface WorkspaceStatus {
  files: number;
  generation?: WorkspaceGeneration | null;
  phase: string;
  references: number;
  root: string;
  roots: WorkspaceRootStatus[];
  stale: boolean;
  stale_summary: string;
  symbols: number;
}
export interface WorkspaceRootStatus {
  files: number;
  generation?: WorkspaceGeneration | null;
  references: number;
  root: string;
  stale: boolean;
  stale_summary: string;
  symbols: number;
}
export interface QueryError {
  code: string;
  message: string;
}
/**
 * A workspace change pushed to attached clients over a daemon subscription.
 */
export interface WorkspaceEventDto {
  generation?: WorkspaceGeneration | null;
  kind: WorkspaceEventKind;
  stale_summary?: string | null;
}
export interface HandshakeResponse {
  capabilities: CapabilitySet;
  daemon_version: string;
  protocol_version: number;
  workspace_root: string;
  workspace_roots: string[];
}
export interface CapabilitySet {
  commands: string[];
  events: string[];
  queries: string[];
}
export interface QueryRequest {
  consistency: Consistency;
  page: Page;
  query: Query;
}
export interface Page {
  cursor?: QueryCursor | null;
  limit: number;
}
export interface QueryCursor {
  generation?: WorkspaceGeneration | null;
  offset: number;
}
export interface QueryResponse {
  generation?: WorkspaceGeneration | null;
  next_cursor?: QueryCursor | null;
  result: QueryResult;
}
export interface TreeChildrenResult {
  languages: CountDto[];
  prefixes: CountDto[];
  root: string;
  roots: string[];
  rows: TreeNode[];
  scoped_files: number;
  total: number;
  total_files: number;
}
export interface CountDto {
  count: number;
  name: string;
}
export interface TreeNode {
  change_count: number;
  defs: number;
  kind: TreeNodeKind;
  language?: string | null;
  path: string;
  refs: number;
  root: string;
}
export interface SymbolListResult {
  rows: SymbolDto[];
  total: number;
}
export interface SymbolDto {
  file: string;
  id: string;
  kind: string;
  language: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  line_range?: [number, number] | null;
  match_reason?: string | null;
  name: string;
  navigable: boolean;
  root: string;
  score?: number | null;
  signature: string;
  source?: SourceSnippet | null;
  uri: string;
  visibility: string;
}
export interface SourceSnippet {
  file: string;
  first_line: number;
  last_line: number;
  lines: SourceLine[];
}
export interface SourceLine {
  number: number;
  text: string;
}
export interface SymbolInsightsResult {
  files: number;
  kinds: CountDto[];
  languages: CountDto[];
  navigable_symbols: number;
  non_navigable_symbols: number;
  references: number;
  shapes: CountDto[];
  symbols: number;
  top_files_by_refs: CountDto[];
  top_files_by_symbols: CountDto[];
}
export interface SymbolDetailResult {
  source?: SourceSnippet | null;
  symbol: SymbolDto;
}
export interface SymbolUsagesResult {
  direction: UsageDirection;
  incoming_summary?: UsageSummaryDto | null;
  outgoing_summary?: UsageSummaryDto | null;
  rows: UsageDto[];
  target: SymbolDto;
  total: number;
}
export interface UsageSummaryDto {
  contexts: number;
  dominant_prefix: string;
  files: number;
  kinds: CountDto[];
  prefixes: number;
  refs: number;
  shared_helper_signal: string;
  top_actors: CountDto[];
  top_prefixes: CountDto[];
}
export interface UsageDto {
  actor: string;
  context: string;
  direction: UsageDirection;
  endpoint: string;
  file: string;
  kind: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  line_range?: [number, number] | null;
  location: string;
  prefix: string;
  reference: string;
  root: string;
  via?: string | null;
}
export interface ViewSummaryDto {
  anchor: string;
  fragment: string;
  id: string;
  scope: string;
  title?: string | null;
}
export interface ViewBoundaryDto {
  evidence: ViewEvidenceDto[];
  forbid_rules: string[];
  forbids: string[];
  id: string;
  missing: string[];
  owns: string[];
  rationale?: string | null;
  rule_refs: ViewRuleRefDto[];
}
export interface ViewEvidenceDto {
  /**
   * @minItems 2
   * @maxItems 2
   */
  active_slice?: [number, number] | null;
  code: SourceLine[];
  file: string;
  label: string;
  moniker: string;
  selector: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  slice?: [number, number] | null;
}
export interface ViewRuleRefDto {
  id: string;
  present: boolean;
}
export interface ViewGotchaDto {
  check?: string | null;
  evidence: ViewEvidenceDto[];
  id: string;
  missing: string[];
  rationale: string;
  rule_refs: ViewRuleRefDto[];
}
export interface ViewRuleDto {
  domain: string;
  id: string;
  rationale?: string | null;
  severity: string;
}
export interface RulesListResult {
  roots: string[];
  rows: RuleDto[];
  total: number;
}
export interface RuleDto {
  domain: string;
  expanded_expr: string;
  expr: string;
  id: string;
  kind?: string | null;
  lang: string;
  message?: string | null;
  rationale?: string | null;
  require_doc_comment?: string | null;
  root: string;
  severity: string;
}
export interface RulesCheckResult {
  errors: FileErrorDto[];
  exit: string;
  roots: RulesCheckRootResult[];
  rule_reports: RuleReportDto[];
  skip_reasons: CheckSkipReasonDto[];
  summary: CheckSummaryDto;
  violations: ViolationDto[];
}
export interface FileErrorDto {
  error: string;
  path: string;
  root: string;
}
export interface RulesCheckRootResult {
  errors: FileErrorDto[];
  exit: string;
  root: string;
  rule_reports: RuleReportDto[];
  skip_reason?: CheckSkipReasonDto | null;
  summary: CheckSummaryDto;
  violations: ViolationDto[];
}
export interface RuleReportDto {
  antecedent_matches?: number | null;
  domain: string;
  evaluated: number;
  matches: number;
  path?: string | null;
  root: string;
  rule_id: string;
  severity: string;
  violations: number;
  warning?: string | null;
}
export interface CheckSkipReasonDto {
  reason: string;
  root: string;
}
export interface CheckSummaryDto {
  elapsed_ms: number;
  failed_rules: FailedRuleDto[];
  files_scanned: number;
  files_with_errors: number;
  files_with_violations: number;
  total_errors: number;
  total_rule_errors: number;
  total_violations: number;
  total_warnings: number;
}
export interface FailedRuleDto {
  rule_id: string;
  severity: string;
  violations: number;
}
export interface ViolationDto {
  kind: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  lines: [number, number];
  message: string;
  moniker: string;
  path: string;
  root: string;
  rule_id: string;
  severity: string;
}
export interface ChangeReviewResult {
  diagnostics: string[];
  files: ChangeReviewFile[];
  ref_changes: ChangeReviewRef[];
  scope: string;
  summary: ChangeReviewSummary;
  symbol_changes: ChangeReviewSymbol[];
}
export interface ChangeReviewFile {
  analyzable: boolean;
  coverage_explained: boolean;
  disposition: string;
  moved_symbols: number;
  new_path?: string | null;
  new_residual: [number, number][];
  old_path?: string | null;
  old_residual: [number, number][];
  symbol_changes: number;
}
export interface ChangeReviewRef {
  file: string;
  kind: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  new_lines?: [number, number] | null;
  new_target?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  old_lines?: [number, number] | null;
  old_target?: string | null;
  ref_kind: string;
}
export interface ChangeReviewSummary {
  analyzable_files: number;
  files: number;
  ref_changes: number;
  residual_files: number;
  retargeted_refs: number;
  symbol_changes: number;
}
export interface ChangeReviewSymbol {
  body_changed: boolean;
  confidence: string;
  file_moved: boolean;
  header_changed: boolean;
  kind: string;
  new?: ChangeReviewSide | null;
  old?: ChangeReviewSide | null;
  signature_changed: boolean;
  visibility_changed: boolean;
}
export interface ChangeReviewSide {
  file: string;
  identity: string;
  kind: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  lines?: [number, number] | null;
  name: string;
  visibility: string;
}
export interface NotesResult {
  action: string;
  deleted?: NoteDto | null;
  rows: NoteDto[];
  total: number;
}
export interface NoteDto {
  body: string;
  created_by: string;
  id: string;
  kind: string;
  moniker: string;
  resolution: NoteResolutionDto;
  status: string;
  title: string;
  updated_at: string;
}
export interface DaemonRegistryEntry {
  cache_dir?: string | null;
  endpoint: string;
  live_refresh?: string | null;
  pid: number;
  project?: string | null;
  token: string;
  workspace_root: string;
  workspace_roots: string[];
}
export interface DaemonWorkspaceConfig {
  cache_dir?: string | null;
  live_refresh?: string | null;
  project?: string | null;
  roots: string[];
}
