#!/usr/bin/env bash
# Regenerate scripts/dogfood/baselines.tsv from a live pcm_dogfood DB.
# Run AFTER scripts/dogfood.sh has ingested the panel. The output is a
# per-project / per-kind floor used by scripts/dogfood-check.sh to catch
# extractor regressions that silently drop defs or refs.
#
# Usage:
#   scripts/dogfood-baseline.sh                  # writes scripts/dogfood/baselines.tsv
#   FLOOR_RATIO=0.95 scripts/dogfood-baseline.sh # tighten (default 0.95 = -5% tolerance)

set -euo pipefail

PG_BIN="${PG_BIN:-$HOME/.pgrx/17.9/pgrx-install/bin}"
PG_PORT="${PG_PORT:-28817}"
DB="${DB:-pcm_dogfood}"
FLOOR_RATIO="${FLOOR_RATIO:-0.95}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/scripts/dogfood/baselines.tsv"
PSQL="$PG_BIN/psql -h localhost -p $PG_PORT -X -q -A -t -F '|' -v ON_ERROR_STOP=1"

if ! $PG_BIN/psql -h localhost -p "$PG_PORT" -d "$DB" -A -t -c 'SELECT 1' >/dev/null 2>&1; then
	echo "error: cannot connect to $DB on port $PG_PORT. run scripts/dogfood.sh first." >&2
	exit 2
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
	echo "# Regression floors for the dogfood panel. Generated by scripts/dogfood-baseline.sh."
	echo "# Format: project|lang|metric|kind|min"
	echo "# - metric=def       kind = a def kind (method, comment, struct, ...)"
	echo "# - metric=ref       kind = a ref kind (calls, imports_module, ...)"
	echo "# - metric=total     kind ∈ {files, defs, refs}"
	echo "# Floors are floor(actual * ${FLOOR_RATIO}). Regenerate after intentional behavior changes."
	echo "#"
} >"$tmp"

# Per-(project, def_kind) floors
$PSQL -d "$DB" -c "
SELECT
	m.project || '|' || m.lang || '|def|' || d.kind || '|' ||
	GREATEST(1, floor(count(*) * ${FLOOR_RATIO})::bigint)
FROM module m, graph_defs(m.graph) d
GROUP BY m.project, m.lang, d.kind
ORDER BY m.project, d.kind;" >>"$tmp"

# Per-(project, ref_kind) floors
$PSQL -d "$DB" -c "
SELECT
	m.project || '|' || m.lang || '|ref|' || r.kind || '|' ||
	GREATEST(1, floor(count(*) * ${FLOOR_RATIO})::bigint)
FROM module m, graph_refs(m.graph) r
GROUP BY m.project, m.lang, r.kind
ORDER BY m.project, r.kind;" >>"$tmp"

# Per-project totals
$PSQL -d "$DB" -c "
SELECT
	m.project || '|' || m.lang || '|total|files|' ||
	GREATEST(1, floor(count(*) * ${FLOOR_RATIO})::bigint)
FROM module m
GROUP BY m.project, m.lang
ORDER BY m.project;" >>"$tmp"

$PSQL -d "$DB" -c "
SELECT
	m.project || '|' || m.lang || '|total|defs|' ||
	GREATEST(1, floor(sum(array_length(graph_def_monikers(m.graph), 1)) * ${FLOOR_RATIO})::bigint)
FROM module m
GROUP BY m.project, m.lang
ORDER BY m.project;" >>"$tmp"

$PSQL -d "$DB" -c "
SELECT
	m.project || '|' || m.lang || '|total|refs|' ||
	GREATEST(1, floor(sum(array_length(graph_ref_targets(m.graph), 1)) * ${FLOOR_RATIO})::bigint)
FROM module m
GROUP BY m.project, m.lang
ORDER BY m.project;" >>"$tmp"

mkdir -p "$(dirname "$OUT")"
mv "$tmp" "$OUT"
trap - EXIT

lines=$(grep -cvE '^#' "$OUT" || true)
echo "wrote $OUT ($lines floors, ratio=$FLOOR_RATIO)"
